### ISSUE TITLE
Video stream of remote participants created by jitsi-meet not rendered when only 2 participants in conference

### ISSUE THREAD

**Issue by zlguo1996** [zlguo1996/jitsi-party#4]
## Description
Video created by [jitsi-meet](https://beta.meet.jit.si/haselabtest) is not rendered in [dev server](http://localhost:9000/?name=conference-name).
## How to recreate this problem
*Note: the following screenshots are all on `tab2`*
1. Accses to jitsi-meet `tab1`.
2. Open dev server `tab2` (Note: the order of 1 and 2 could not be reversed, or the video would correctly be shown). The result would like the following (remote video is not displayed):
![image](https://user-images.githubusercontent.com/17405914/82774081-c536eb00-9e7e-11ea-93da-a40e128d51c5.png)
3. Open another dev website `tab3`, the video should be shown: 
![image](https://user-images.githubusercontent.com/17405914/82774130-edbee500-9e7e-11ea-9dce-e9e6d0010e0b.png)
(When there are three participants in the conference, the order of enter does not matter. Video could always be shown)

**Comment by VirgiliaBeatrice** [comment]
This video rendering problem happens when adding remote tracks.
The console log showed that the JitsiConference.TrackAdded event had been invoked twice when reproducing this problem.

This behavior is expected as a normal one in lib-jitsi-meet, which happens when a remote connection shifted to a P2P connection.
The property of `isP2P` in JitsiRemoteParticipant indicates the state of that.

Currently, we will fix this problem with a temporary solution that the video will only be rendered when a P2P connection has been established.
For the future, an alternative solution is expected.
