### ISSUE TITLE
Remote video does not has meta data: width & height

### ISSUE THREAD

**Issue by zlguo1996** [zlguo1996/jitsi-party#5]
## Todos
Need add [MediaTrackSettings](https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackSettings) for remote video track:
- width
- height
- aspectRatio  
  
Both `dummy connection` and camera & screen capture video should contain those data.

## Verify
The following error message would shown if width & height is not provided.
![image](https://user-images.githubusercontent.com/17405914/82776656-96247780-9e86-11ea-8038-3de209853571.png)

## Why need those data
The data is used to set parent div border to make the video avatar round.

**Comment by VirgiliaBeatrice** [comment]
This problem is caused by the MediaStreamTrack obtained from RtcPeerConnection, which does not contain video width and height information.
The MediaStreamTrack obtained from RtcPeerConnection only has capabilities of `deviceId`, `facingMode`, and `resizeMode`, just like `{deviceId: "c8ec961a-f6d4-485d-8d0a-8db25e17e246", facingMode: Array(0), resizeMode: Array(2)}`.

To obtain video width, height, and other information, it is better to use a video element that is also used by WebRTC official samples.

Another solution is to use RTCPeerConnection's data channel to negotiate.

Reference: 
https://webrtc.github.io/samples/

**Comment by zlguo1996** [comment]
The meta data from remote stream is not needed now. Because we can use `videoTag.videoWidth` and `videoTag.videoHeight` to get aspect ratio.
